---
title: "ggplot theme"
author: "Morris Greenberg"
date: "12/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sample Theme:

```{r theme_proj, echo=F}
theme_proj <- ggplot2::theme(legend.position="bottom",
        legend.direction="horizontal",
        legend.key = element_rect(fill="white"),
        text = element_text(family="serif", size = 11, color = "black"),
        panel.background = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        plot.title = element_text(family="serif", size = 12, face = "bold", 
 hjust=0.5, margin = margin(b = 20, r=0, l=0, t=20)),
        plot.caption = element_text(family="serif", hjust = 0),
        strip.background = element_blank(), 
        axis.line = element_line(color="black", size = .25),
        axis.ticks.x  = element_blank(),
        axis.text.x=element_text (color = "black"),
        axis.text.y=element_text (color = "black"))
```